site_name: Via Foundry Documentation
theme:
  name: material
  logo: 'images/via_icon.png'
  palette:
    primary: white
copyright: Â© 2023 by Via Scientific
site_author: Via Foundry Team

plugins:
    - search
    - mkdocs-video


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

extra_css: [css/custom.css]

extra:
  generator: false

nav:
  - Home: index.md
  - Getting Started:
    - 'Platform Overview': ViaFoundry/overview.md
    - 'Pipeline Examples': ViaFoundry/pipeline_example.md
    - 'About': ViaFoundry/about.md
    - 'How To Cite Us': ViaFoundry/cite.md
  - Tutorials:
    - 'Running RNA-Seq Pipeline': ViaFoundry/demo_rna-seq_tutorial.md
    - 'Running Cellranger Pipeline': ViaFoundry/demo_single_cell_rna-seq_tutorial.md
    - 'Using Metadata Tracker - GEO': ViaFoundry/demo_metadata-geo.md
    - 'Developer Tutorial - Pipeline Creation (novice)': ViaFoundry/demo_developer_tutorial.md
    - 'Developer Tutorial 2 - Pipeline Creation (advanced)': ViaFoundry/hisat_dev_tutorial.md
      
  - User Guide:
    - 'Quick Start Guide': ViaFoundry/quick.md
    - 'Project Guide': ViaFoundry/project.md
    - 'Run Guide': ViaFoundry/run.md
    - 'App Guide': ViaFoundry/app.md
    - 'Profile Guide': ViaFoundry/profile.md
    - 'Metadata Guide': ViaFoundry/metadata_guide.md
    - 'Frequently Asked Questions': ViaFoundry/faq.md
  - Developer Guide:
    - 'Pipeline Creation Guide': ViaFoundry/pipeline_guide.md
    - 'Process Creation Guide': ViaFoundry/process.md
    - 'V-Meta API v1': ViaFoundry/vmeta_api.md
  - Developer FAQs:
    - 'General FAQs': ViaFoundry/developer_faq.md
    - 'Process FAQs': ViaFoundry/process_faq.md
    - 'Pipeline FAQs': ViaFoundry/pipeline_faq.md
    - 'Third Party FAQs': ViaFoundry/third_party_faq.md
  - Administrator Guide:
    - 'Installation': ViaFoundry/admin-installation.md
    - 'Configuration': ViaFoundry/admin-configuration.md
    - 'Testing Pipeline': ViaFoundry/admin-pipeline-testing.md
